services:
  - type: web
    name: mri-classification-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt gunicorn
    startCommand: cd backend && python scripts/download_model.py && gunicorn -w 4 "app:create_app()"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: HF_MODEL_REPO
        value: phangrisani/MRI-Classification
      - key: CORS_ALLOWED_ORIGINS
        fromService:
          name: mri-classification-frontend
          type: web
          property: host
    healthCheckPath: /
    disk:
      name: mri-data
      mountPath: /opt/render/project/src/results
      sizeGB: 1

  - type: web
    name: mri-classification-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: mri-classification-backend
          type: web
          property: host
          append: /api
